"""Russian names for the system nutrition catalog, keyed by the English name.

Used by ``seed_nutrition_products.py`` and by the migration that backfills
names for catalogs that were seeded before Russian was added.
"""

RU_NAMES = {
    "Chicken breast": "Куриное филе",
    "Chicken thigh": "Куриное бедро",
    "Turkey breast": "Филе индейки",
    "Lean beef": "Говядина постная",
    "Lean pork": "Свинина постная",
    "Salmon": "Лосось",
    "Canned tuna": "Тунец консервированный",
    "Mackerel": "Скумбрия",
    "Shrimp": "Креветки",
    "Egg": "Яйцо",
    "Egg white": "Яичный белок",
    "Greek yogurt": "Греческий йогурт",
    "Plain yogurt": "Йогурт натуральный",
    "Cottage cheese 5%": "Творог 5%",
    "Cottage cheese 2%": "Творог 2%",
    "Hard cheese": "Твёрдый сыр",
    "Mozzarella": "Моцарелла",
    "Oatmeal": "Овсянка",
    "White rice, dry": "Рис белый сухой",
    "Brown rice, dry": "Рис коричневый сухой",
    "Buckwheat, dry": "Гречка сухая",
    "Quinoa, dry": "Киноа сухая",
    "Pasta, dry": "Макароны сухие",
    "Whole wheat pasta": "Цельнозерновые макароны",
    "White bread": "Хлеб пшеничный",
    "Whole grain bread": "Хлеб цельнозерновой",
    "Wheat tortilla": "Тортилья пшеничная",
    "Potato": "Картофель",
    "Sweet potato": "Батат",
    "Corn": "Кукуруза",
    "Red kidney beans, cooked": "Красная фасоль варёная",
    "Chickpeas, cooked": "Нут варёный",
    "Lentils, cooked": "Чечевица варёная",
    "Broccoli": "Брокколи",
    "Cauliflower": "Цветная капуста",
    "Spinach": "Шпинат",
    "Tomato": "Помидор",
    "Cucumber": "Огурец",
    "Carrot": "Морковь",
    "Bell pepper": "Болгарский перец",
    "Avocado": "Авокадо",
    "Apple": "Яблоко",
    "Banana": "Банан",
    "Orange": "Апельсин",
    "Strawberry": "Клубника",
    "Blueberries": "Черника",
    "Raspberries": "Малина",
    "Peanuts": "Арахис",
    "Almonds": "Миндаль",
    "Walnuts": "Грецкие орехи",
    "Peanut butter": "Арахисовая паста",
    "Olive oil": "Оливковое масло",
    "Honey": "Мёд",
    "Dark chocolate 70%": "Тёмный шоколад 70%",
    "Black coffee": "Кофе чёрный",
    "Espresso": "Эспрессо",
    "Americano": "Американо",
    "Black tea": "Чай чёрный",
    "Green tea": "Чай зелёный",
    "Herbal tea": "Травяной чай",
    "Iced tea, sweetened": "Холодный чай сладкий",
    "Milk 2.5%": "Молоко 2.5%",
    "Milk 1.5%": "Молоко 1.5%",
    "Kefir 2.5%": "Кефир 2.5%",
    "Ayran": "Айран",
    "Soy drink, unsweetened": "Соевый напиток без сахара",
    "Almond drink, unsweetened": "Миндальный напиток без сахара",
    "Coconut water": "Кокосовая вода",
    "Orange juice": "Апельсиновый сок",
    "Apple juice": "Яблочный сок",
    "Grape juice": "Виноградный сок",
    "Tomato juice": "Томатный сок",
    "Lemonade": "Лимонад",
    "Cola": "Кола",
    "Sports drink": "Спортивный напиток",
    "Energy drink": "Энергетический напиток",
    "Sparkling water": "Газированная вода",
    "Water": "Вода",
}
