WEAK_MUSCLE_SCORE = 8.0
OVERLOAD_PENALTY = 12.0

PATTERN_SCORE = 3.0
PATTERN_OVERLOAD_PENALTY = 7.0

DIFFICULTY_PENALTY = 4.0
RISK_PENALTY = 3.0

DIVERSITY_BONUS = 2.0
REPEATED_EXERCISE_PENALTY = 2.0

FREQUENCY_HIGH = 8
FREQUENCY_LOW = 2
FREQUENCY_PENALTY = 3.0
FREQUENCY_BONUS = 2.0

PROGRESSION_SCORE = 3.0
PLATEAU_SCORE = 2.0
REGRESSION_SCORE = 4.0

LOW_DIVERSITY_THRESHOLD = 0.35
MEDIUM_DIVERSITY_THRESHOLD = 0.60

PATTERN_LOW_THRESHOLD = 0.15
PATTERN_HIGH_THRESHOLD = 0.35

PROGRESSION_MIN_WEEKS = 2
PROGRESSION_GOOD_THRESHOLD = 0.15
PROGRESSION_REGRESSION_THRESHOLD = -0.10
PROGRESSION_PLATEAU_THRESHOLD = 0.05

RECOVERY_GOOD_SLEEP = 7.0
RECOVERY_MEDIUM_SLEEP = 6.0

RECOVERY_GOOD_FATIGUE = 3.0
RECOVERY_MEDIUM_FATIGUE = 5.0

RECOVERY_GOOD_STRESS = 4.0
RECOVERY_MEDIUM_STRESS = 6.0

RECOVERY_GOOD_SORENESS = 3.0
RECOVERY_MEDIUM_SORENESS = 5.0

RECOVERY_PENALTY = 8.0
RECOVERY_MODERATE_PENALTY = 3.0

USER_LEVEL_BEGINNER = "beginner"
USER_LEVEL_INTERMEDIATE = "intermediate"
USER_LEVEL_ADVANCED = "advanced"

SUMMARY_PRIORITY = {
    "recovery": 4,
    "load": 3,
    "muscles": 2,
    "patterns": 1,
}
