"""nutrition model types and constraints

Revision ID: 30742736f6de
Revises: 5e9b0a4563c9
Create Date: 2026-09-01 17:58:42.574948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30742736f6de'
down_revision = '5e9b0a4563c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_category_user_name', ['user_id', 'name'])

    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.alter_column('protein',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('fat',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('carbs',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('fiber',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_meal_items_meal_id'), ['meal_id'], unique=False)
        batch_op.drop_column('category_label')

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.alter_column('total_protein',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('total_fat',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('total_carbs',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_meals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('nutrition_plans', schema=None) as batch_op:
        batch_op.alter_column('protein',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('fats',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('carbs',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_nutrition_plans_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('saved_meals', schema=None) as batch_op:
        batch_op.alter_column('protein',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('fat',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('carbs',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_saved_meals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.alter_column('protein_goal',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('fat_goal',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('carb_goal',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('user_goals_user_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_goals_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('user_water', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_water_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_water_date', ['user_id', 'date'])

    with op.batch_alter_table('user_weight_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_weight_history_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_weight_date', ['user_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_weight_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_weight_date', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_weight_history_user_id'))

    with op.batch_alter_table('user_water', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_water_date', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_water_user_id'))
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_goals_user_id'))
        batch_op.create_unique_constraint(batch_op.f('user_goals_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('carb_goal',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('fat_goal',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('protein_goal',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('saved_meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_meals_user_id'))
        batch_op.alter_column('carbs',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('fat',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('protein',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('nutrition_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_plans_user_id'))
        batch_op.alter_column('carbs',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('fats',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('protein',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meals_user_id'))
        batch_op.alter_column('total_carbs',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('total_fat',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('total_protein',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('meal_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_meal_items_meal_id'))
        batch_op.alter_column('fiber',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('carbs',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('fat',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('protein',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_category_user_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))

    # ### end Alembic commands ###
