"""sync training plan and performance state schema

Revision ID: 78213daccdf5
Revises: 0dec34ec765f
Create Date: 2026-09-23 12:34:31.117685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78213daccdf5'
down_revision = '0dec34ec765f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.alter_column('sets_planned',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('te_performance_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('te_training_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', postgresql.JSONB(astext_type=sa.Text()), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_performance_state_id_fkey'), type_='foreignkey')
        batch_op.drop_column('performance_state_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performance_state_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('users_performance_state_id_fkey'), 'te_performance_state', ['performance_state_id'], ['id'])

    with op.batch_alter_table('te_training_plans', schema=None) as batch_op:
        batch_op.drop_column('days')

    with op.batch_alter_table('te_performance_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('session_exercises', schema=None) as batch_op:
        batch_op.alter_column('sets_planned',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
